# $FreeBSD$

PORTNAME=            pakchois
PORTVERSION=         0.4
CATEGORIES=          devel
MASTER_SITES=        http://www.manyfish.co.uk/pakchois/
#MASTER_SITE_SUBDIR=  pakchois/

MAINTAINER=     spam@amrx.net
COMMENT=        PKCS #11 wrapper library

GNU_CONFIGURE=  yes
CONFIGURE_ARGS= --without-libintl-prefix

.include <bsd.port.mk>
